### ISSUE TITLE
Show error when first HAP reload is done instead of panicking

### ISSUE THREAD

**Issue by nyodas** [blablacar/go-synapse#27]
##All-in-title
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6751da]

goroutine 112 [running]:
panic(0x8828e0, 0xc4200120a0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/blablacar/go-synapse/vendor/github.com/n0rad/go-erlog.(*ErlogWriterAppender).logError(0xc420190620, 0xc420192230, 0xc420264380, 0xb32440, 0x0)
	/home/n0rad/Work/go/src/github.com/blablacar/go-synapse/vendor/github.com/n0rad/go-erlog/formatter.go:139 +0xaa
github.com/blablacar/go-synapse/vendor/github.com/n0rad/go-erlog.(*ErlogWriterAppender).logError(0xc420190620, 0xc420192230, 0xc420264380, 0xb32440, 0xc4201fea80)
	/home/n0rad/Work/go/src/github.com/blablacar/go-synapse/vendor/github.com/n0rad/go-erlog/formatter.go:185 +0x75b
github.com/blablacar/go-synapse/vendor/github.com/n0rad/go-erlog.(*ErlogWriterAppender).Fire(0xc420190620, 0xc420264380)
	/home/n0rad/Work/go/src/github.com/blablacar/go-synapse/vendor/github.com/n0rad/go-erlog/formatter.go:125 +0x8ec
github.com/blablacar/go-synapse/vendor/github.com/n0rad/go-erlog.(*ErlogLogger).log(0xc420190640, 0xc420264380)
	/home/n0rad/Work/go/src/github.com/blablacar/go-synapse/vendor/github.com/n0rad/go-erlog/logger.go:48 +0x5e
github.com/blablacar/go-synapse/vendor/github.com/n0rad/go-erlog.(*ErlogLogger).LogEntry(0xc420190640, 0xc4201fa540)
	/home/n0rad/Work/go/src/github.com/blablacar/go-synapse/vendor/github.com/n0rad/go-erlog/logger.go:141 +0xc4
github.com/blablacar/go-synapse/vendor/github.com/n0rad/go-erlog/logs.(*Entry).Error(0xc4201fa540, 0x913add, 0x23)
	/home/n0rad/Work/go/src/github.com/blablacar/go-synapse/vendor/github.com/n0rad/go-erlog/logs/entry.go:101 +0x5f
github.com/blablacar/go-synapse/synapse.(*RouterCommon).handleReport(0xc4200b7cc0, 0xc42000e400, 0x3, 0x4, 0xb3a440, 0xc4200b7cc0)
	/home/n0rad/Work/go/src/github.com/blablacar/go-synapse/synapse/router.go:139 +0x708
github.com/blablacar/go-synapse/synapse.(*RouterCommon).eventsProcessor.func1()
	/home/n0rad/Work/go/src/github.com/blablacar/go-synapse/synapse/router.go:83 +0x331
created by time.goFunc
	/usr/lib/go/src/time/sleep.go:154 +0x44
```

**Comment by n0rad** [comment]
fixed in v12
